service:
  debug: true
  logFile: "jwt_service.log"

JWT:
  secret: "JWT Secret"

token:
  expirationMinutes:
    access: 7200
    refresh: 43200
    fresh: 20

messages:
  invalidToken: "Token is invalid"
  expiredToken: "Token has expired"